
FROM node:18

WORKDIR /app

COPY package*.json ./

#set up staging environment env file
COPY $ENV_FILE_STAGING .env.staging


RUN npm install

COPY . .

RUN npm run build

FROM node:18

WORKDIR /app

COPY --from=builder /app/.output ./.output
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

ENV NITRO_PRESET=node

CMD ["node", ".output/server/index.mjs"]
